[build]
    command = "npm run build"
    
[[redirects]]
    from = "https://radenpioneer.netlify.app/*"
    to = "https://radenpioneer.xyz/:splat"
    status = 301
    force = true

[dev]
    command = "npm run dev"
    port = 4000