[build]
    command = "npm run prod"
    publish = "dist/"
    
[[redirects]]
    from = "https://radenpioneer.netlify.app/*"
    to = "https://radenpioneer.xyz/:splat"
    status = 301
    force = true

[dev]
    command = "npm start"
    port = 4000