[build]
    command = "cross-env ELEVENTY_ENV=prod npm run build"
    publish = "dist/"
    
[dev]
    command = "npm start"
    autoLaunch = false

[[plugins]]
    package = "./plugins/netlify/cache"