# .github/workflows/main.yml

name: Annual Build
on:
  schedule:
    - cron: '0 1 1 1 *'
jobs:
  build:
    name: Netlify Annual Build
    runs-on: ubuntu-latest
    steps:
      - name: Curl request
        run: curl -X POST -d {} ${{ secrets.NETLIFY_BUILD_HOOK }}
