# .github/workflows/main.yml

name: Monthly Build
on:
  schedule:
    - cron: '30 4 15 * *'
jobs:
  build:
    name: Netlify Annual Build
    runs-on: ubuntu-latest
    steps:
      - name: Curl request
        run: curl -X POST -d {} ${{ secrets.NETLIFY_BUILD_HOOK }}
